# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo da Atividade')),
                ('duracao', models.CharField(max_length=50, verbose_name='Tempo de duração')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo da atividade')),
                ('quantidadeParticipantes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=55, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo do Evento')),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio do evento')),
                ('dataTermino', models.DateField(verbose_name='Data do Termino do evento')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apppalestras.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Participante')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=250, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppalestras.Pessoa')),
                ('minicurriculo', models.TextField(verbose_name='Minicurriculo')),
            ],
            bases=('apppalestras.pessoa',),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppalestras.Pessoa')),
            ],
            bases=('apppalestras.pessoa',),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apppalestras.Evento'),
        ),
        migrations.AddField(
            model_name='participante',
            name='atividade',
            field=models.ManyToManyField(to='apppalestras.Atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='palestrante',
            field=models.ManyToManyField(to='apppalestras.Palestrante'),
        ),
    ]
