# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppalestras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='quantidadeParticipantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='apppalestras.Pessoa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='apppalestras.Pessoa'),
        ),
    ]
